### ISSUE TITLE
Jack error

### ISSUE THREAD

**Issue by Tusenka** [deezer/Android-Aspectj-Plugin#1]
Thank you for your plugin.
I am using Intellij with Android and AspectJ plugin.
When I add the plguin to graddle the error appear:

Gradle sync failed: Cannot cast object 'task ':app:transformJackWithJackForDebug'' with class 'com.android.build.gradle.internal.pipeline.TransformTask_Decorated' to class 'org.gradle.api.tasks.compile.JavaCompile'

**Comment by xgouchet** [comment]
Hi Tusenka, 
the AspectJ plugin is not compatible with the Jack compiling tools, and as Google officially dropped Jack & Jill's support, we probably won't be investing time on this feature.

**Comment by Tusenka** [comment]
Thank you for your answer. I go to war with IntelliJ for supporting Java 8 into the default toolchain.
